<?php
// รับข้อมูลจากฟอร์ม
$fname = $_POST['fname'];
$Nname = $_POST['lname'];
$Nameeng = $_POST['Nameeng'];
$gender = $_POST['gender'];
$job = $_POST['job'];
$salary = $_POST['salary'];
$salary_period = $_POST['salary_period'];
$no = $_POST['no'];
$group = $_POST['group'];
$road = $_POST['road'];
$district = $_POST['district'];
$county = $_POST['county'];
$province = $_POST['province'];
$Postalcode = $_POST['Postalcode'];
$email = $_POST['email'];
$nonow = $_POST['nonow'];
$groupnow = $_POST['groupnow'];
$roadnow = $_POST['roadnow'];
$districtnow = $_POST['districtnow'];
$countynow = $_POST['countynow'];
$provincenow = $_POST['aprovincenow'];
$Postalcodenow = $_POST['Postalcodenow'];
$phonehomenow = $_POST['phonehomenow'];
$phonenow = $_POST['phonenow'];
$whoathome = $_POST['whoathome'];
$birthday = $_POST['birthday'];
$age = $_POST['age'];
$height = $_POST['height'];
$weight = $_POST['weight'];
$nationality = $_POST['nationality'];
$ethnicity = $_POST['ethnicity'];
$religion = $_POST['religion'];
$noid = $_POST['noid'];
$whereid = $_POST['whereid'];
$idexpire = $_POST['idexpire'];
$taxpayerid = $_POST['taxpayerid'];
$socialsecurityid = $_POST['socialsecurityid'];
$militarycondition = $_POST['militarycondition'];
$qualifiedmilitary_year = $_POST['qualifiedmilitary_year'];
$status = $_POST['status'];
$statusmarry = $_POST['statusmarry'];
$spouse = $_POST['spouse'];
$wherespousejob = $_POST['wherespousejob'];
$positionspouse = $_POST['positionspouse'];
$havebaby = $_POST['havebaby'];
$badystuding = $_POST['badystuding'];
$badynotstuding = $_POST['badynotstuding'];

// แสดงข้อมูลที่ได้รับ
echo "<h1>ข้อมูลที่ได้รับจากฟอร์ม</h1>";
echo "<p>ชื่อ - นามสกุล: $fname</p>";
echo "<p>ชื่อเล่น: $Nname</p>";
echo "<p>Name in English: $Nameeng</p>";
echo "<p>เพศ: $gender</p>";
echo "<p>สมัครตำแหน่ง: $job</p>";
echo "<p>เงินเดือนที่ต้องการ: $salary บาท/ $salary_period</p>";
echo "<p>ที่อยู่ตามทะเบียนบ้าน: เลขที่ $no หมู่ที่ $group ถนน $road ตำบล/แขวง $district อำเภอ/เขต $county จังหวัด $province รหัสไปรษณีย์ $Postalcode</p>";
echo "<p>อีเมล: $email</p>";
echo "<p>ที่อยู่ปัจจุบัน: เลขที่ $nonow หมู่ที่ $groupnow ถนน $roadnow ตำบล/แขวง $districtnow อำเภอ/เขต $countynow จังหวัด $provincenow รหัสไปรษณีย์ $Postalcodenow โทรศัพท์: $phonehomenow มือถือ: $phonenow</p>";
echo "<p>บ้านที่อาศัยอยู่: $whoathome</p>";
echo "<p>วัน เดือน ปีเกิด: $birthday</p>";
echo "<p>อายุ: $age ปี</p>";
echo "<p>ส่วนสูง: $height</p>";
echo "<p>น้ำหนัก: $weight กก.</p>";
echo "<p>สัญชาติ: $nationality</p>";
echo "<p>เชื้อชาติ: $ethnicity</p>";
echo "<p>ศาสนา: $religion</p>";
echo "<p>บัตรประชาชนเลขที่: $noid</p>";
echo "<p>สถานที่ออกบัตร: $whereid</p>";
echo "<p>บัตรหมดอายุ: $idexpire</p>";
echo "<p>บัตรผู้เสียภาษีเลขที่: $taxpayerid</p>";
echo "<p>บัตรประกันสังคมเลขที่: $socialsecurityid</p>";
echo "<p>สภาพทางทหาร: $militarycondition</p>";
echo "<p>ปีที่เกณฑ์: $qualifiedmilitary_year</p>";
echo "<p>สถานภาพ: $status</p>";
echo "<p>กรณีแต่งงาน: $statusmarry</p>";
echo "<p>ชื่อภรรยา/สามี: $spouse</p>";
echo "<p>ชื่อสถานที่ทำงาน: $wherespousejob</p>";
echo "<p>ตำแหน่ง: $positionspouse</p>";
echo "<p>มีบุตร: $havebaby คน</p>";
echo "<p>จำนวนบุตรที่กำลังศึกษา: $badystuding คน</p>";
echo "<p>จำนวนบุตรที่ยังไม่เข้าศึกษา: $badynotstuding คน</p>";
?>
